services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    volumes:
      - db_data:/app/data
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    init: true
    ports:
      - "80:80"
      - "8443:443"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: