services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    volumes:
      - db_data:/app/data
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://localhost:8443
      - DATABASE_PATH=file:/app/data/database.sqlite
      - GOOGLE_OAUTH_START_REDIRECT_PATH=/api/session/google
      - GOOGLE_OAUTH_TOKEN_URL=https://oauth2.googleapis.com/token
      - GOOGLE_OAUTH_USER_INFO_URL=https://www.googleapis.com/oauth2/v2/userinfo
      - GOOGLE_CALLBACK_URL=https://localhost:8443/api/session/google/callback
    restart: unless-stopped
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    init: true
    ports:
      - "8443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge