services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
      - db_data:/app/data
    ports:
      # Exposing the backend API for development
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_PATH=file:/app/data/database.sqlite
      - JWT_SECRET=dev-jwt-secret-replace-in-prod
      - COOKIE_SECRET=dev-cookie-secret-replace-in-prod
      - SESSION_SECRET=dev-session-secret-replace-in-prod
      - GOOGLE_OAUTH_START_REDIRECT_PATH=/api/session/google
      - GOOGLE_OAUTH_TOKEN_URL=https://oauth2.googleapis.com/token
      - GOOGLE_OAUTH_USER_INFO_URL=https://www.googleapis.com/oauth2/v2/userinfo
      - GOOGLE_CALLBACK_URL=http://localhost:5173/api/session/google/callback
    restart: unless-stopped
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    init: true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/index.html:/app/index.html
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge